name: inventory_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  image_picker: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  intl: ^0.19.0
  csv: ^5.0.2
  pdf: ^3.10.4
  mobile_scanner: ^3.5.2
  uuid: ^4.3.3
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_barcode_scanner: ^2.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true